bot:
  name: ${BOT_NAME}
  key: ${BOT_KEY}

ru:
  wallentos:
    carworker:
      manager-link: T.me/mikhail_ung
      admin-list: Mikhail_Ung, wallentos
      client-request-group-id: -1001801658754
      exchange-coefficient: ${COEFFICIENT}
      extra-pay-corea:
        krw: 2500000
        rub: 70000
      extra-pay-china:
        cny: 25000
        rub: 250000
      exchange-api:
        host-cbr: https://www.cbr-xml-daily.ru/daily_json.js
        host-naver: https://finance.naver.com/marketindex/exchangeDetail.nhn?marketindexCd=FX_USDKRW
        host-encar: https://fem.encar.com/cars/detail/
        host-che-start: https://www.che168.com/CarConfig/CarConfig.html
        host-che-detail: https://cacheapigo.che168.com/CarProduct/GetParam.ashx?
      update-cache-job:
        master-bot: false
        cron: 0 0/30 * * * *

spring:
  data:
    redis:
      password: ${REDIS_PASSWORD}
      host: ${REDIS_HOST}
      port: '6472'
      timeout: '60000'
