bot:
  name: ${BOT_NAME}
  key: ${BOT_KEY}

ru:
  wallentos:
    carworker:
      korex-mode: false
      enable-krw-link-mode: false
      manager-link: T.me/mikhail_ung
      admin-id: 126866786
      exchange-coefficient: ${COEFFICIENT}
      extra-pay-corea:
        krw: 2500000
        rub: 70000
      extra-pay-china:
        cny: 2500000
        rub: 70000
      exchange-api:
        host-cbr: https://www.cbr-xml-daily.ru/daily_json.js
        host-naver: https://finance.naver.com/marketindex/exchangeDetail.nhn?marketindexCd=FX_USDKRW
        host-encar: https://fem.encar.com/cars/detail/
      update-cache-job:
        master-bot: false
        cron: 0 0/30 * * * *
        
spring:
  data:
    redis:
      password: ${REDIS_PASSWORD}
      host: ${REDIS_HOST}
      port: '6472'
      timeout: '60000'
