bot:
  name: KorexManagerBot

ru:
  wallentos:
    carworker:
      currencies: KRW, CNY
      enable-krw-link-mode: ${ENABLE_KRW_LINK_MODE}
      enable-cny-link-mode: ${ENABLE_CNY_LINK_MODE}
      manager-logistics-spreedsheet-id: ${MANAGER_LOGISTICS_SPREDSHEET_ID}
      disable-double-convertation: true
      exchange-manager-coefficient: ${MANAGER_COEFFICIENT}
      manager-link: https://t.me/Mikhail_Ung
      manager-bot: true
      white-manager-list: ${MANAGER_WHITELIST}
      parent-link: t.me/KorexCalcBot
      user-prefix: "user_manager_"
      extra-pay-corea:
        krw: 2040000
        rub: 100000
      extra-pay-china:
        cny: 15000
        rub: 120000
  