bot:
  name: EastWayCalcBot
  
ru:
  wallentos:
    carworker:
      currencies: KRW, CNY
      enable-krw-link-mode: ${ENABLE_KRW_LINK_MODE}
      enable-cny-link-mode: ${ENABLE_CNY_LINK_MODE}
      enable-krw-auction-mode: true
      auction-coefficient: ${AUCTION_COEFFICIENT}
      disable-double-convertation: true
      manager-link: https://t.me/EastWayAdmin
      client-request-group-id: -1001812961296
      user-prefix: "user_east_"
      extra-pay-corea:
        krw: 3500000
        rub: 130000
      extra-pay-china:
        cny: 18000
        rub: 170000
