bot:
  name: TempACalcBot

ru:
  wallentos:
    carworker:
      manager-link: https://t.me/tempazakaz
      extra-pay-corea:
        krw: 2500000
        rub: 190000
      extra-pay-china:
        cny: 25000
        rub: 250000
