bot:
  name: KorexCalcBot
  
ru:
  wallentos:
    carworker:
      currencies: KRW, CNY
      enable-krw-link-mode: ${ENABLE_KRW_LINK_MODE}
      enable-cny-link-mode: ${ENABLE_CNY_LINK_MODE}
      korex-province-matrix: true
      client-request-spreedsheet-id: 160dFiu2oswiYji4QUI-mlUVuFoTzH-sqX1OlQvaFuIc
      client-request-group-id: -1001854156002
      enable-client-request: ${ENABLE_CLIENT_REQUEST}
      disable-double-convertation: true
      enable-encar-report-mode: true
      enable-result-detalization: true
      check-channel-subscribers: true
      is-cbr-rate-to-calculate: true
      channel-subscribers-id: -1001423584530
      channel-subscribers-link: https://t.me/korex_official
      manager-link: T.me/Korex_Consultant
      user-prefix: "user_korex_"
      extra-pay-corea:
        krw: ${EXTRA_PAY_KOREA_KRW}
        rub: ${EXTRA_PAY_KOREA_RUB}
      extra-pay-china:
        cny: ${EXTRA_PAY_CHINA_CNY}
        rub: ${EXTRA_PAY_CHINA_RUB}
      update-cache-job:
        master-bot: true
