bot:
  name: EastWayCalcBot
  
ru:
  wallentos:
    carworker:
      currencies: KRW, CNY
      enable-krw-link-mode: ${ENABLE_KRW_LINK_MODE}
      enable-cny-link-mode: ${ENABLE_CNY_LINK_MODE}
      client-request-spreedsheet-id: ${CLIENT_REQUEST_SPREEDSHEET_ID}
      disable-double-convertation: true
      manager-link: https://t.me/EastWayAdmin
      client-request-group-id: -1001812961296
      enable-client-request: true
      user-prefix: "user_east_"
      admin-list: ${ADMIN_LIST}
      extra-pay-corea:
        krw: ${EXTRA_PAY_KOREA_KRW}
        rub: ${EXTRA_PAY_KOREA_RUB}
      extra-pay-china:
        cny: ${EXTRA_PAY_CHINA_CNY}
        rub: ${EXTRA_PAY_CHINA_RUB}
