bot:
  name: DemoCarBot

ru:
  wallentos:
    carworker:
      currencies: KRW, CNY
      enable-krw-link-mode: ${ENABLE_KRW_LINK_MODE}
      enable-cny-link-mode: ${ENABLE_CNY_LINK_MODE}
      enable-krw-auction-mode: true
      auction-coefficient: ${AUCTION_COEFFICIENT}
      disable-double-convertation: true
      manager-link: https://t.me/Korexkorea
      user-prefix: "user_korex_demo_"
      client-request-group-id: -1001720826075
      enable-client-request: true
      client-request-spreedsheet-id: ${CLIENT_REQUEST_SPREEDSHEET_ID}
      extra-pay-corea:
        krw: 2040000
        rub: 100000
      extra-pay-china:
        cny: 15000
        rub: 100000
  