bot:
  name: KorexCalcBot
  
ru:
  wallentos:
    carworker:
      korex-mode: true
      enable-krw-link-mode: true
      manager-link: https://t.me/korexadmin
      extra-pay-corea:
        krw: 2500000
        rub: 100000
