bot:
  name: AutoDillerBot

ru:
  wallentos:
    carworker:
      currencies: KRW, CNY
      enable-krw-link-mode: ${ENABLE_KRW_LINK_MODE}
      enable-cny-link-mode: ${ENABLE_CNY_LINK_MODE}
      client-request-spreedsheet-id: ${CLIENT_REQUEST_SPREEDSHEET_ID}
      enable-krw-auction-mode: true
      auction-coefficient: ${AUCTION_COEFFICIENT}
      manager-link: https://t.me/Roman_autodiler
      client-request-group-id: -1001950549646
      enable-client-request: true
      user-prefix: "user_rostov_"
      admin-list: ${ADMIN_LIST}
      extra-pay-corea:
        krw: 4000000
        rub: 200000
      extra-pay-china:
        cny: 26000
        rub: 200000
  