bot:
  name: GreenAngleBot

ru:
  wallentos:
    carworker:
      manager-link: https://t.me/mikhail_ung
      user-prefix: "user_green_"
      currencies: KRW, CNY
      extra-pay-corea:
        krw: 2500000
        rub: 130000
      extra-pay-china:
        cny: 25000
        rub: 200000