ru:
  wallentos:
    carworker:
      currencies: KRW, CNY
      enable-krw-link-mode: true
      enable-cny-link-mode: true
      enable-krw-auction-mode: true
      manager-link: https://t.me/wallentoss
      user-prefix: "user_test_"
      client-request-spreedsheet-id: ${CLIENT_REQUEST_SPREEDSHEET_ID}
      update-cache-job:
        master-bot: ${IS_MASTER_BOT}
        cron: ${CRON}
        