bot:
  name: KorexCalcBot
  
ru:
  wallentos:
    carworker:
      currencies: KRW
      enable-krw-link-mode: ${ENABLE_KRW_LINK_MODE}
      enable-krw-auction-mode: true
      auction-coefficient: ${AUCTION_COEFFICIENT}
      manager-link: https://t.me/korexadmin
      extra-pay-corea:
        krw: 2500000
        rub: 100000
      update-cache-job:
        master-bot: true
