bot:
  name: HotCarCalcBot
  
ru:
  wallentos:
    carworker:
      manager-link: https://t.me/xbest88
      extra-pay-corea:
        krw: 2500000
        rub: 100000
      extra-pay-china:
        cny: 25000
        rub: 200000
