ru:
  wallentos:
    carworker:
      korex-mode: false
      currencies: KRW
      enable-krw-link-mode: true
      enable-krw-auction-mode: true
      manager-link: https://t.me/wallentoss
      user-prefix: "user_test_"
      update-cache-job:
        master-bot: ${IS_MASTER_BOT}
        cron: ${CRON}
        