bot:
  name: EastWayCalcBot
  
ru:
  wallentos:
    carworker:
      korex-mode: true
      currencies: KRW
      enable-krw-link-mode: ${ENABLE_KRW_LINK_MODE}
      manager-link: https://t.me/Mikhail_Ung
      extra-pay-corea:
        krw: 2500000
        rub: 180000
