bot:
  name: MCARCalcBot

ru:
  wallentos:
    carworker:
      currencies: KRW, CNY
      enable-krw-link-mode: ${ENABLE_KRW_LINK_MODE}
      enable-cny-link-mode: ${ENABLE_CNY_LINK_MODE}
      client-request-spreedsheet-id: ${CLIENT_REQUEST_SPREEDSHEET_ID}
      client-request-group-id: -1002007059186
      enable-client-request: ${ENABLE_CLIENT_REQUEST}
      enable-result-detalization: true
      manager-link: T.me/Konstantin_k12
      user-prefix: "user_mcar_"
      extra-pay-corea:
        krw: ${EXTRA_PAY_KOREA_KRW}
        rub: ${EXTRA_PAY_KOREA_RUB}
      extra-pay-china:
        cny: ${EXTRA_PAY_CHINA_CNY}
        rub: ${EXTRA_PAY_CHINA_RUB}
      admin-list: ${ADMIN_LIST}
  