ru:
  wallentos:
    carworker:
      exchange-coefficient: ${COEFFICIENT}
      exchange-api:
        host: https://v6.exchangerate-api.com/
        method: /v6/${EXCHANGE_KEY}/latest/EUR
bot:
  name: ${BOT_NAME}
  key: ${BOT_KEY}