ru:
  wallentos:
    carworker:
      currencies: KRW, CNY
      enable-krw-link-mode: true
      enable-cny-link-mode: true
      enable-krw-auction-mode: true
      manager-link: https://t.me/wallentoss
      user-prefix: "user_test_"
      client-request-spreedsheet-id: ${CLIENT_REQUEST_SPREEDSHEET_ID}
      client-request-group-id: -1001801658754
      manager-logistics-spreedsheet-id: 1BkK8M7KNuR4Rp8VQciQL2tuFinEBFd2sNLD1KlpwoSc
      enable-client-request: true
      enable-encar-report-mode: true
      enable-result-detalization: true
      check-channel-subscribers: true
      channel-subscribers-id: -1002123611967
      channel-subscribers-link: https://t.me/MikhailValTest
      update-cache-job:
        master-bot: ${IS_MASTER_BOT}
        cron: ${CRON}
        