bot:
  name: HotCarCalcBot
  
ru:
  wallentos:
    carworker:
      manager-link: https://t.me/xbest88
      user-prefix: "user_hot_"
      currencies: KRW, CNY
      admin-list: ${ADMIN_LIST}
      extra-pay-corea:
        krw: ${EXTRA_PAY_KOREA_KRW}
        rub: ${EXTRA_PAY_KOREA_RUB}
      extra-pay-china:
        cny: ${EXTRA_PAY_CHINA_CNY}
        rub: ${EXTRA_PAY_CHINA_RUB}
