bot:
  name: ${BOT_NAME}
  key: ${BOT_KEY}

ru:
  wallentos:
    carworker:
      disable-china: false
      manager-link: T.me/mikhail_ung
      exchange-coefficient: ${COEFFICIENT}
      extra-pay-corea:
        krw: 2500000
        rub: 70000
      extra-pay-china:
        cny: 2500000
        rub: 70000
      exchange-api:
        host-cbr: https://www.cbr-xml-daily.ru/daily_json.js
