package ru.wallentos.carworker.model;

/**
 * Возможные состояния бота
 */

public enum BotState {
    SET_CURRENCY_MENU,
    MAILING_MENU,
    SET_CURRENCY,
    ASK_CURRENCY_MANUAL_MODE,
    ASK_PRICE,
    ASK_ISSUE_DATE,
    ASK_VOLUME,
    ASK_CALCULATION_MODE,
    WAITING_FOR_LINK,
    DATA_PREPARED,
    ASK_AUCTION_START_PRICE,
    ASK_CLIENT_REQUEST_MESSAGE,
    ASK_AUCTION_VOLUME,
    ASK_AUCTION_ISSUE_DATE,
    ASK_CLIENT_CONTACT,
    ASK_CHINA_LINK
}